stages:
  load_data: 
    cmd: python src/load_data.py --config=params.yaml
    deps:
      - src/get_data.py
      - src/load_data.py
      - data/raw/insur.csv

    outs:
      - data/raw/insur.csv

  split_data:
    cmd: python src/split_data.py --config=params.yaml
    deps:
      - src/split_data.py
      - data/raw/insur.csv
    outs:
      - data/processed/train_insurance.csv
      - data/processed/test_insurance.csv

  train_and_evaluate:
    cmd: python src/train_and_evaluate.py --config=params.yaml
    deps:
      - src/train_and_evaluate.py
      - data/processed/train_insurance.csv
      - data/processed/test_insurance.csv
    params:
      - estimators.ElasticNet.params.alpha
      - estimators.ElasticNet.params.l1_ratio

    metrics:
      - reports/scores.json
        cache: false
      - reports/params.json
        cache: false

    outs:
      - models/model.joblib